name: GitHub - Activity - README

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  
jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          Activity_Token: ${{ secrets.ACTIVITY_TOKEN}}
        with:
          COMMIT_MSG: "Specify a custom commit message"
          MAX_LINES: 10
          COMMIT_NAME: GitHub Activity Readme
